name: health_life
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  share_plus: ^11.0.0
  file_saver: ^0.2.14
  provider: ^6.1.2
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.1.0
  flutter_local_notifications: ^19.3.0 # This is a very recent version, good!
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4 # This dependency is correct

# >>>>>>>>>> IMPORTANT CHANGE HERE: MOVE THIS BLOCK OUTSIDE OF 'flutter:' <<<<<<<<<<
flutter_launcher_icons: # This should be a TOP-LEVEL key
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon1.png"
  min_sdk_android: 21
# <<<<<<<<<< END OF MOVED BLOCK <<<<<<<<<<

flutter_lints: ^5.0.0

flutter: # This 'flutter' block should *not* contain flutter_launcher_icons configuration
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/times.ttf
    - assets/fonts/AyarJuno-2LO8.ttf